### ISSUE TITLE
Virus detected by Chrome

### ISSUE THREAD

**Issue by vivadavid** [stuerp/foo_midi#32]
Hi,

I've tried to download version 2.9.2.0, but Chrome has displayed the warning "virus detected" and has blocked the download.

I have Chrome 120 running on Windows 11 (23H2).

**Comment by Maxkatsur** [comment]
Same issue; I use Opera as a browser and Avast as an antivirus program. Also, I mixed foo_midi with foo_vgmstream for Foobar2000, and the latter audio player crashed! Ouch.

**Comment by vivadavid** [comment]
This is what Windows Securiy has reported:

![Virus detected by Chrome](https://github.com/stuerp/foo_midi/assets/9334287/6cfc05cb-eb67-43ea-9706-de278ccdeb91)

**Comment by stuerp** [comment]
Why report that here? It's a bug in Chrome. There's nothing I can and want to do about it.

**Comment by vivadavid** [comment]
Hi,

The problem is not limited to Chrome and Windows Security, as another user wrote earlier that the same issue was experienced with Opera and Avast.

I've reported it here because this is the repository for the software. It's probably just a false positive, and now it's up to you to find out what happened or just leave it as it is.

**Comment by stuerp** [comment]
Sorry for the cranky response but I've just had another long discussion on the support forum about the same issue. Most virus detection engines seem to steal definitions from each other causing these false positives to pop up all over the place.

It's probably the .exe's in the archive that cause the detection engine to go nuts because the DLL calls CreateProcess to launch it and communicates with it over a pipe. A perfectly legit use case. In any case that code hasn't change for nearly a year and suddenly it is suspect...

And and don't think Microsoft owned GitHub would allow me to upload virus infected binaries.

**Comment by vivadavid** [comment]
No problem! When I see a virus alert, I find it a good idea to report it to the developer, so that they can decide if there's something to do about it. I know that false positives are annoying, and they can discourage users who don't know about them from using the software, when the sofware is, in fact, perfectly fine.

By the way, I tried to download it a second time and I was succesful. Then I uploaded the file to Virus Total, where only Avast and McAfee reported an alert.

Now, I've tried to download it a third time and Chrome has blocked it again. Weird.
