### ISSUE TITLE
Sound is too big?

### ISSUE THREAD

**Issue by yuishin-kikuchi** [stuerp/foo_midi#49]
foo_midi 2.10.0.0 with foobar 2000 v2.1.5 (x64)

I'm using VSTi (Yamaha S-YXG50).
When I play favourite MIDI with foo_midi, the sound distorted.
So I configured Yamaha S-YXG50 to volume down (-3 db), the sound is genuine.

Are there any troubles in vsthost?
Or, doubly played?
I wish fixed.

thanks

**Comment by stuerp** [comment]
vshost simply loads the VST, passes the MIDI commands to the VST for rendering and sends the generated samples to foobar2000 for playing: absolutely no processing.
But: if you're mixing 32-bit and 64-bit foobar and VST's there can be some clipping due to the conversion from 32-bit floats the 64-bit doubles.
Which architecture combination are you using?

**Comment by stuerp** [comment]
No feedback from issuer.
